<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Milvus\Proto\Common;

use UnexpectedValueException;

/**
 * Protobuf type <code>milvus.proto.common.CompactionState</code>
 */
class CompactionState
{
    /**
     * Generated from protobuf enum <code>UndefiedState = 0;</code>
     */
    const UndefiedState = 0;
    /**
     * Generated from protobuf enum <code>Executing = 1;</code>
     */
    const Executing = 1;
    /**
     * Generated from protobuf enum <code>Completed = 2;</code>
     */
    const Completed = 2;

    private static $valueToName = [
        self::UndefiedState => 'UndefiedState',
        self::Executing => 'Executing',
        self::Completed => 'Completed',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

