<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Milvus\Proto\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.common.PrivilegeExt</code>
 */
class PrivilegeExt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ObjectType object_type = 1;</code>
     */
    protected $object_type = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.ObjectPrivilege object_privilege = 2;</code>
     */
    protected $object_privilege = 0;
    /**
     * Generated from protobuf field <code>int32 object_name_index = 3;</code>
     */
    protected $object_name_index = 0;
    /**
     * Generated from protobuf field <code>int32 object_name_indexs = 4;</code>
     */
    protected $object_name_indexs = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $object_type
     *     @type int $object_privilege
     *     @type int $object_name_index
     *     @type int $object_name_indexs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ObjectType object_type = 1;</code>
     * @return int
     */
    public function getObjectType()
    {
        return $this->object_type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ObjectType object_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setObjectType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\ObjectType::class);
        $this->object_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ObjectPrivilege object_privilege = 2;</code>
     * @return int
     */
    public function getObjectPrivilege()
    {
        return $this->object_privilege;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.ObjectPrivilege object_privilege = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setObjectPrivilege($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\ObjectPrivilege::class);
        $this->object_privilege = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 object_name_index = 3;</code>
     * @return int
     */
    public function getObjectNameIndex()
    {
        return $this->object_name_index;
    }

    /**
     * Generated from protobuf field <code>int32 object_name_index = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setObjectNameIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->object_name_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 object_name_indexs = 4;</code>
     * @return int
     */
    public function getObjectNameIndexs()
    {
        return $this->object_name_indexs;
    }

    /**
     * Generated from protobuf field <code>int32 object_name_indexs = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setObjectNameIndexs($var)
    {
        GPBUtil::checkInt32($var);
        $this->object_name_indexs = $var;

        return $this;
    }

}

