<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: segcore.proto

namespace GPBMetadata;

class Segcore
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Schema::initOnce();
        $pool->internalAddGeneratedFile(
            '
è
segcore.protomilvus.proto.segcore"}
RetrieveResults%
ids (2.milvus.proto.schema.IDs
offset (3
fields_data (2.milvus.proto.schema.FieldData"P
LoadFieldMeta
min_timestamp (
max_timestamp (
	row_count ("Y
LoadSegmentMeta2
metas (2#.milvus.proto.segcore.LoadFieldMeta

total_size ("U
InsertRecord3
fields_data (2.milvus.proto.schema.FieldData
num_rows (B6Z4github.com/milvus-io/milvus/internal/proto/segcorepbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

