<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.CheckHealthResponse</code>
 */
class CheckHealthResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>bool isHealthy = 2;</code>
     */
    protected $isHealthy = false;
    /**
     * Generated from protobuf field <code>repeated string reasons = 3;</code>
     */
    private $reasons;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.QuotaState quota_states = 4;</code>
     */
    private $quota_states;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type bool $isHealthy
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $reasons
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $quota_states
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isHealthy = 2;</code>
     * @return bool
     */
    public function getIsHealthy()
    {
        return $this->isHealthy;
    }

    /**
     * Generated from protobuf field <code>bool isHealthy = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsHealthy($var)
    {
        GPBUtil::checkBool($var);
        $this->isHealthy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string reasons = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReasons()
    {
        return $this->reasons;
    }

    /**
     * Generated from protobuf field <code>repeated string reasons = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReasons($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->reasons = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.QuotaState quota_states = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQuotaStates()
    {
        return $this->quota_states;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.QuotaState quota_states = 4;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQuotaStates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Milvus\Proto\Milvus\QuotaState::class);
        $this->quota_states = $arr;

        return $this;
    }

}

