<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.CreateCredentialRequest</code>
 */
class CreateCredentialRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * username
     *
     * Generated from protobuf field <code>string username = 2;</code>
     */
    protected $username = '';
    /**
     * ciphertext password
     *
     * Generated from protobuf field <code>string password = 3;</code>
     */
    protected $password = '';
    /**
     * create time
     *
     * Generated from protobuf field <code>uint64 created_utc_timestamps = 4;</code>
     */
    protected $created_utc_timestamps = 0;
    /**
     * modify time
     *
     * Generated from protobuf field <code>uint64 modified_utc_timestamps = 5;</code>
     */
    protected $modified_utc_timestamps = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           Not useful for now
     *     @type string $username
     *           username
     *     @type string $password
     *           ciphertext password
     *     @type int|string $created_utc_timestamps
     *           create time
     *     @type int|string $modified_utc_timestamps
     *           modify time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * username
     *
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * username
     *
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * ciphertext password
     *
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * ciphertext password
     *
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * create time
     *
     * Generated from protobuf field <code>uint64 created_utc_timestamps = 4;</code>
     * @return int|string
     */
    public function getCreatedUtcTimestamps()
    {
        return $this->created_utc_timestamps;
    }

    /**
     * create time
     *
     * Generated from protobuf field <code>uint64 created_utc_timestamps = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedUtcTimestamps($var)
    {
        GPBUtil::checkUint64($var);
        $this->created_utc_timestamps = $var;

        return $this;
    }

    /**
     * modify time
     *
     * Generated from protobuf field <code>uint64 modified_utc_timestamps = 5;</code>
     * @return int|string
     */
    public function getModifiedUtcTimestamps()
    {
        return $this->modified_utc_timestamps;
    }

    /**
     * modify time
     *
     * Generated from protobuf field <code>uint64 modified_utc_timestamps = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setModifiedUtcTimestamps($var)
    {
        GPBUtil::checkUint64($var);
        $this->modified_utc_timestamps = $var;

        return $this;
    }

}

