<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.DescribeSegmentResponse</code>
 */
class DescribeSegmentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     */
    protected $indexID = 0;
    /**
     * Generated from protobuf field <code>int64 buildID = 3;</code>
     */
    protected $buildID = 0;
    /**
     * Generated from protobuf field <code>bool enable_index = 4;</code>
     */
    protected $enable_index = false;
    /**
     * Generated from protobuf field <code>int64 fieldID = 5;</code>
     */
    protected $fieldID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type int|string $indexID
     *     @type int|string $buildID
     *     @type bool $enable_index
     *     @type int|string $fieldID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     * @return int|string
     */
    public function getIndexID()
    {
        return $this->indexID;
    }

    /**
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndexID($var)
    {
        GPBUtil::checkInt64($var);
        $this->indexID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 buildID = 3;</code>
     * @return int|string
     */
    public function getBuildID()
    {
        return $this->buildID;
    }

    /**
     * Generated from protobuf field <code>int64 buildID = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBuildID($var)
    {
        GPBUtil::checkInt64($var);
        $this->buildID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_index = 4;</code>
     * @return bool
     */
    public function getEnableIndex()
    {
        return $this->enable_index;
    }

    /**
     * Generated from protobuf field <code>bool enable_index = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableIndex($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 5;</code>
     * @return int|string
     */
    public function getFieldID()
    {
        return $this->fieldID;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldID($var)
    {
        GPBUtil::checkInt64($var);
        $this->fieldID = $var;

        return $this;
    }

}

