<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.GrantPrivilegeEntity</code>
 */
class GrantPrivilegeEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.GrantorEntity entities = 1;</code>
     */
    private $entities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Milvus\Proto\Milvus\GrantorEntity>|\Google\Protobuf\Internal\RepeatedField $entities
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.GrantorEntity entities = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntities()
    {
        return $this->entities;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.GrantorEntity entities = 1;</code>
     * @param array<\Milvus\Proto\Milvus\GrantorEntity>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Milvus\GrantorEntity::class);
        $this->entities = $arr;

        return $this;
    }

}

