<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ImportRequest</code>
 */
class ImportRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * target collection
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     */
    protected $collection_name = '';
    /**
     * target partition
     *
     * Generated from protobuf field <code>string partition_name = 2;</code>
     */
    protected $partition_name = '';
    /**
     * channel names for the collection
     *
     * Generated from protobuf field <code>repeated string channel_names = 3;</code>
     */
    private $channel_names;
    /**
     * the file is row-based or column-based
     *
     * Generated from protobuf field <code>bool row_based = 4;</code>
     */
    protected $row_based = false;
    /**
     * file paths to be imported
     *
     * Generated from protobuf field <code>repeated string files = 5;</code>
     */
    private $files;
    /**
     * import options, bucket, etc.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair options = 6;</code>
     */
    private $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection_name
     *           target collection
     *     @type string $partition_name
     *           target partition
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $channel_names
     *           channel names for the collection
     *     @type bool $row_based
     *           the file is row-based or column-based
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $files
     *           file paths to be imported
     *     @type array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $options
     *           import options, bucket, etc.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * target collection
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * target collection
     *
     * Generated from protobuf field <code>string collection_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * target partition
     *
     * Generated from protobuf field <code>string partition_name = 2;</code>
     * @return string
     */
    public function getPartitionName()
    {
        return $this->partition_name;
    }

    /**
     * target partition
     *
     * Generated from protobuf field <code>string partition_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPartitionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->partition_name = $var;

        return $this;
    }

    /**
     * channel names for the collection
     *
     * Generated from protobuf field <code>repeated string channel_names = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChannelNames()
    {
        return $this->channel_names;
    }

    /**
     * channel names for the collection
     *
     * Generated from protobuf field <code>repeated string channel_names = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChannelNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->channel_names = $arr;

        return $this;
    }

    /**
     * the file is row-based or column-based
     *
     * Generated from protobuf field <code>bool row_based = 4;</code>
     * @return bool
     */
    public function getRowBased()
    {
        return $this->row_based;
    }

    /**
     * the file is row-based or column-based
     *
     * Generated from protobuf field <code>bool row_based = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRowBased($var)
    {
        GPBUtil::checkBool($var);
        $this->row_based = $var;

        return $this;
    }

    /**
     * file paths to be imported
     *
     * Generated from protobuf field <code>repeated string files = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * file paths to be imported
     *
     * Generated from protobuf field <code>repeated string files = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->files = $arr;

        return $this;
    }

    /**
     * import options, bucket, etc.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair options = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * import options, bucket, etc.
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair options = 6;</code>
     * @param array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->options = $arr;

        return $this;
    }

}

