<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Index informations
 *
 * Generated from protobuf message <code>milvus.proto.milvus.IndexDescription</code>
 */
class IndexDescription extends \Google\Protobuf\Internal\Message
{
    /**
     * Index name
     *
     * Generated from protobuf field <code>string index_name = 1;</code>
     */
    protected $index_name = '';
    /**
     * Index id
     *
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     */
    protected $indexID = 0;
    /**
     * Will return index_type, metric_type, params(like nlist).
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair params = 3;</code>
     */
    private $params;
    /**
     * The vector field name
     *
     * Generated from protobuf field <code>string field_name = 4;</code>
     */
    protected $field_name = '';
    /**
     * index build progress
     *
     * Generated from protobuf field <code>int64 indexed_rows = 5;</code>
     */
    protected $indexed_rows = 0;
    /**
     * Generated from protobuf field <code>int64 total_rows = 6;</code>
     */
    protected $total_rows = 0;
    /**
     * index state
     *
     * Generated from protobuf field <code>.milvus.proto.common.IndexState state = 7;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>string index_state_fail_reason = 8;</code>
     */
    protected $index_state_fail_reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $index_name
     *           Index name
     *     @type int|string $indexID
     *           Index id
     *     @type array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $params
     *           Will return index_type, metric_type, params(like nlist).
     *     @type string $field_name
     *           The vector field name
     *     @type int|string $indexed_rows
     *           index build progress
     *     @type int|string $total_rows
     *     @type int $state
     *           index state
     *     @type string $index_state_fail_reason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Index name
     *
     * Generated from protobuf field <code>string index_name = 1;</code>
     * @return string
     */
    public function getIndexName()
    {
        return $this->index_name;
    }

    /**
     * Index name
     *
     * Generated from protobuf field <code>string index_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_name = $var;

        return $this;
    }

    /**
     * Index id
     *
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     * @return int|string
     */
    public function getIndexID()
    {
        return $this->indexID;
    }

    /**
     * Index id
     *
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndexID($var)
    {
        GPBUtil::checkInt64($var);
        $this->indexID = $var;

        return $this;
    }

    /**
     * Will return index_type, metric_type, params(like nlist).
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair params = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Will return index_type, metric_type, params(like nlist).
     *
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair params = 3;</code>
     * @param array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->params = $arr;

        return $this;
    }

    /**
     * The vector field name
     *
     * Generated from protobuf field <code>string field_name = 4;</code>
     * @return string
     */
    public function getFieldName()
    {
        return $this->field_name;
    }

    /**
     * The vector field name
     *
     * Generated from protobuf field <code>string field_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;

        return $this;
    }

    /**
     * index build progress
     *
     * Generated from protobuf field <code>int64 indexed_rows = 5;</code>
     * @return int|string
     */
    public function getIndexedRows()
    {
        return $this->indexed_rows;
    }

    /**
     * index build progress
     *
     * Generated from protobuf field <code>int64 indexed_rows = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndexedRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->indexed_rows = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_rows = 6;</code>
     * @return int|string
     */
    public function getTotalRows()
    {
        return $this->total_rows;
    }

    /**
     * Generated from protobuf field <code>int64 total_rows = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_rows = $var;

        return $this;
    }

    /**
     * index state
     *
     * Generated from protobuf field <code>.milvus.proto.common.IndexState state = 7;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * index state
     *
     * Generated from protobuf field <code>.milvus.proto.common.IndexState state = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\IndexState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string index_state_fail_reason = 8;</code>
     * @return string
     */
    public function getIndexStateFailReason()
    {
        return $this->index_state_fail_reason;
    }

    /**
     * Generated from protobuf field <code>string index_state_fail_reason = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexStateFailReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_state_fail_reason = $var;

        return $this;
    }

}

