<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.OperatePrivilegeRequest</code>
 */
class OperatePrivilegeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * grant
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.GrantEntity entity = 2;</code>
     */
    protected $entity = null;
    /**
     * operation type
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.OperatePrivilegeType type = 3;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           Not useful for now
     *     @type \Milvus\Proto\Milvus\GrantEntity $entity
     *           grant
     *     @type int $type
     *           operation type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * grant
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.GrantEntity entity = 2;</code>
     * @return \Milvus\Proto\Milvus\GrantEntity|null
     */
    public function getEntity()
    {
        return $this->entity;
    }

    public function hasEntity()
    {
        return isset($this->entity);
    }

    public function clearEntity()
    {
        unset($this->entity);
    }

    /**
     * grant
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.GrantEntity entity = 2;</code>
     * @param \Milvus\Proto\Milvus\GrantEntity $var
     * @return $this
     */
    public function setEntity($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Milvus\GrantEntity::class);
        $this->entity = $var;

        return $this;
    }

    /**
     * operation type
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.OperatePrivilegeType type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * operation type
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.OperatePrivilegeType type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Milvus\OperatePrivilegeType::class);
        $this->type = $var;

        return $this;
    }

}

