<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.SelectRoleRequest</code>
 */
class SelectRoleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * role
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RoleEntity role = 2;</code>
     */
    protected $role = null;
    /**
     * include user info
     *
     * Generated from protobuf field <code>bool include_user_info = 3;</code>
     */
    protected $include_user_info = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           Not useful for now
     *     @type \Milvus\Proto\Milvus\RoleEntity $role
     *           role
     *     @type bool $include_user_info
     *           include user info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * role
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RoleEntity role = 2;</code>
     * @return \Milvus\Proto\Milvus\RoleEntity|null
     */
    public function getRole()
    {
        return $this->role;
    }

    public function hasRole()
    {
        return isset($this->role);
    }

    public function clearRole()
    {
        unset($this->role);
    }

    /**
     * role
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.RoleEntity role = 2;</code>
     * @param \Milvus\Proto\Milvus\RoleEntity $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Milvus\RoleEntity::class);
        $this->role = $var;

        return $this;
    }

    /**
     * include user info
     *
     * Generated from protobuf field <code>bool include_user_info = 3;</code>
     * @return bool
     */
    public function getIncludeUserInfo()
    {
        return $this->include_user_info;
    }

    /**
     * include user info
     *
     * Generated from protobuf field <code>bool include_user_info = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeUserInfo($var)
    {
        GPBUtil::checkBool($var);
        $this->include_user_info = $var;

        return $this;
    }

}

