<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.ShardReplica</code>
 */
class ShardReplica extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 leaderID = 1;</code>
     */
    protected $leaderID = 0;
    /**
     * IP:port
     *
     * Generated from protobuf field <code>string leader_addr = 2;</code>
     */
    protected $leader_addr = '';
    /**
     * Generated from protobuf field <code>string dm_channel_name = 3;</code>
     */
    protected $dm_channel_name = '';
    /**
     * optional, DO NOT save it in meta, set it only for GetReplicas()
     * if with_shard_nodes is true
     *
     * Generated from protobuf field <code>repeated int64 node_ids = 4;</code>
     */
    private $node_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $leaderID
     *     @type string $leader_addr
     *           IP:port
     *     @type string $dm_channel_name
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $node_ids
     *           optional, DO NOT save it in meta, set it only for GetReplicas()
     *           if with_shard_nodes is true
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 leaderID = 1;</code>
     * @return int|string
     */
    public function getLeaderID()
    {
        return $this->leaderID;
    }

    /**
     * Generated from protobuf field <code>int64 leaderID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLeaderID($var)
    {
        GPBUtil::checkInt64($var);
        $this->leaderID = $var;

        return $this;
    }

    /**
     * IP:port
     *
     * Generated from protobuf field <code>string leader_addr = 2;</code>
     * @return string
     */
    public function getLeaderAddr()
    {
        return $this->leader_addr;
    }

    /**
     * IP:port
     *
     * Generated from protobuf field <code>string leader_addr = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLeaderAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->leader_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dm_channel_name = 3;</code>
     * @return string
     */
    public function getDmChannelName()
    {
        return $this->dm_channel_name;
    }

    /**
     * Generated from protobuf field <code>string dm_channel_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDmChannelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dm_channel_name = $var;

        return $this;
    }

    /**
     * optional, DO NOT save it in meta, set it only for GetReplicas()
     * if with_shard_nodes is true
     *
     * Generated from protobuf field <code>repeated int64 node_ids = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNodeIds()
    {
        return $this->node_ids;
    }

    /**
     * optional, DO NOT save it in meta, set it only for GetReplicas()
     * if with_shard_nodes is true
     *
     * Generated from protobuf field <code>repeated int64 node_ids = 4;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNodeIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->node_ids = $arr;

        return $this;
    }

}

