<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use UnexpectedValueException;

/**
 * Deprecated: use GetLoadingProgress rpc instead
 *
 * Protobuf type <code>milvus.proto.milvus.ShowType</code>
 */
class ShowType
{
    /**
     * Will return all collections
     *
     * Generated from protobuf enum <code>All = 0;</code>
     */
    const All = 0;
    /**
     * Will return loaded collections with their inMemory_percentages
     *
     * Generated from protobuf enum <code>InMemory = 1;</code>
     */
    const InMemory = 1;

    private static $valueToName = [
        self::All => 'All',
        self::InMemory => 'InMemory',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

