<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * List all partitions for particular collection
 *
 * Generated from protobuf message <code>milvus.proto.milvus.ShowPartitionsRequest</code>
 */
class ShowPartitionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * The collection name you want to describe, you can pass collection_name or collectionID
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * The collection id in milvus
     *
     * Generated from protobuf field <code>int64 collectionID = 4;</code>
     */
    protected $collectionID = 0;
    /**
     * When type is InMemory, will return these patitions's inMemory_percentages.(Optional)
     *
     * Generated from protobuf field <code>repeated string partition_names = 5;</code>
     */
    private $partition_names;
    /**
     * Decide return Loaded partitions or All partitions(Optional)
     * Deprecated: use GetLoadingProgress rpc instead
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.ShowType type = 6;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *           Not useful for now
     *     @type string $db_name
     *           Not useful for now
     *     @type string $collection_name
     *           The collection name you want to describe, you can pass collection_name or collectionID
     *     @type int|string $collectionID
     *           The collection id in milvus
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $partition_names
     *           When type is InMemory, will return these patitions's inMemory_percentages.(Optional)
     *     @type int $type
     *           Decide return Loaded partitions or All partitions(Optional)
     *           Deprecated: use GetLoadingProgress rpc instead
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

    /**
     * The collection name you want to describe, you can pass collection_name or collectionID
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * The collection name you want to describe, you can pass collection_name or collectionID
     *
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * The collection id in milvus
     *
     * Generated from protobuf field <code>int64 collectionID = 4;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * The collection id in milvus
     *
     * Generated from protobuf field <code>int64 collectionID = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * When type is InMemory, will return these patitions's inMemory_percentages.(Optional)
     *
     * Generated from protobuf field <code>repeated string partition_names = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPartitionNames()
    {
        return $this->partition_names;
    }

    /**
     * When type is InMemory, will return these patitions's inMemory_percentages.(Optional)
     *
     * Generated from protobuf field <code>repeated string partition_names = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPartitionNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->partition_names = $arr;

        return $this;
    }

    /**
     * Decide return Loaded partitions or All partitions(Optional)
     * Deprecated: use GetLoadingProgress rpc instead
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.ShowType type = 6;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Decide return Loaded partitions or All partitions(Optional)
     * Deprecated: use GetLoadingProgress rpc instead
     *
     * Generated from protobuf field <code>.milvus.proto.milvus.ShowType type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Milvus\ShowType::class);
        $this->type = $var;

        return $this;
    }

}

