<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: milvus.proto

namespace Milvus\Proto\Milvus;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.milvus.UpsertRequest</code>
 */
class UpsertRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     */
    protected $collection_name = '';
    /**
     * Generated from protobuf field <code>string partition_name = 4;</code>
     */
    protected $partition_name = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     */
    private $fields_data;
    /**
     * Generated from protobuf field <code>repeated uint32 hash_keys = 6;</code>
     */
    private $hash_keys;
    /**
     * Generated from protobuf field <code>uint32 num_rows = 7;</code>
     */
    protected $num_rows = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $db_name
     *     @type string $collection_name
     *     @type string $partition_name
     *     @type array<\Milvus\Proto\Schema\FieldData>|\Google\Protobuf\Internal\RepeatedField $fields_data
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $hash_keys
     *     @type int $num_rows
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Milvus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string partition_name = 4;</code>
     * @return string
     */
    public function getPartitionName()
    {
        return $this->partition_name;
    }

    /**
     * Generated from protobuf field <code>string partition_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPartitionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->partition_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldsData()
    {
        return $this->fields_data;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     * @param array<\Milvus\Proto\Schema\FieldData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldsData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldData::class);
        $this->fields_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 hash_keys = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHashKeys()
    {
        return $this->hash_keys;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 hash_keys = 6;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHashKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->hash_keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_rows = 7;</code>
     * @return int
     */
    public function getNumRows()
    {
        return $this->num_rows;
    }

    /**
     * Generated from protobuf field <code>uint32 num_rows = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setNumRows($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_rows = $var;

        return $this;
    }

}

