<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace Milvus\Proto\Msg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.msg.CreateCollectionRequest</code>
 */
class CreateCollectionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string collectionName = 3;</code>
     */
    protected $collectionName = '';
    /**
     * Generated from protobuf field <code>string partitionName = 4;</code>
     */
    protected $partitionName = '';
    /**
     * `schema` is the serialized `schema.CollectionSchema`
     *
     * Generated from protobuf field <code>int64 dbID = 5;</code>
     */
    protected $dbID = 0;
    /**
     * Generated from protobuf field <code>int64 collectionID = 6;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>int64 partitionID = 7;</code>
     */
    protected $partitionID = 0;
    /**
     * Generated from protobuf field <code>bytes schema = 8;</code>
     */
    protected $schema = '';
    /**
     * Generated from protobuf field <code>repeated string virtualChannelNames = 9;</code>
     */
    private $virtualChannelNames;
    /**
     * Generated from protobuf field <code>repeated string physicalChannelNames = 10;</code>
     */
    private $physicalChannelNames;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $db_name
     *     @type string $collectionName
     *     @type string $partitionName
     *     @type int|string $dbID
     *           `schema` is the serialized `schema.CollectionSchema`
     *     @type int|string $collectionID
     *     @type int|string $partitionID
     *     @type string $schema
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $virtualChannelNames
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $physicalChannelNames
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collectionName = 3;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collectionName;
    }

    /**
     * Generated from protobuf field <code>string collectionName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->collectionName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string partitionName = 4;</code>
     * @return string
     */
    public function getPartitionName()
    {
        return $this->partitionName;
    }

    /**
     * Generated from protobuf field <code>string partitionName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPartitionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->partitionName = $var;

        return $this;
    }

    /**
     * `schema` is the serialized `schema.CollectionSchema`
     *
     * Generated from protobuf field <code>int64 dbID = 5;</code>
     * @return int|string
     */
    public function getDbID()
    {
        return $this->dbID;
    }

    /**
     * `schema` is the serialized `schema.CollectionSchema`
     *
     * Generated from protobuf field <code>int64 dbID = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbID($var)
    {
        GPBUtil::checkInt64($var);
        $this->dbID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 6;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 partitionID = 7;</code>
     * @return int|string
     */
    public function getPartitionID()
    {
        return $this->partitionID;
    }

    /**
     * Generated from protobuf field <code>int64 partitionID = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->partitionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes schema = 8;</code>
     * @return string
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * Generated from protobuf field <code>bytes schema = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, False);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string virtualChannelNames = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVirtualChannelNames()
    {
        return $this->virtualChannelNames;
    }

    /**
     * Generated from protobuf field <code>repeated string virtualChannelNames = 9;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVirtualChannelNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->virtualChannelNames = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string physicalChannelNames = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPhysicalChannelNames()
    {
        return $this->physicalChannelNames;
    }

    /**
     * Generated from protobuf field <code>repeated string physicalChannelNames = 10;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPhysicalChannelNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->physicalChannelNames = $arr;

        return $this;
    }

}

