<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace Milvus\Proto\Msg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.msg.DeleteRequest</code>
 */
class DeleteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>string shardName = 2;</code>
     */
    protected $shardName = '';
    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     */
    protected $collection_name = '';
    /**
     * Generated from protobuf field <code>string partition_name = 5;</code>
     */
    protected $partition_name = '';
    /**
     * Generated from protobuf field <code>int64 dbID = 6;</code>
     */
    protected $dbID = 0;
    /**
     * Generated from protobuf field <code>int64 collectionID = 7;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>int64 partitionID = 8;</code>
     */
    protected $partitionID = 0;
    /**
     * deprecated
     *
     * Generated from protobuf field <code>repeated int64 int64_primary_keys = 9;</code>
     */
    private $int64_primary_keys;
    /**
     * Generated from protobuf field <code>repeated uint64 timestamps = 10;</code>
     */
    private $timestamps;
    /**
     * Generated from protobuf field <code>int64 num_rows = 11;</code>
     */
    protected $num_rows = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs primary_keys = 12;</code>
     */
    protected $primary_keys = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type string $shardName
     *     @type string $db_name
     *     @type string $collection_name
     *     @type string $partition_name
     *     @type int|string $dbID
     *     @type int|string $collectionID
     *     @type int|string $partitionID
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $int64_primary_keys
     *           deprecated
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $timestamps
     *     @type int|string $num_rows
     *     @type \Milvus\Proto\Schema\IDs $primary_keys
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shardName = 2;</code>
     * @return string
     */
    public function getShardName()
    {
        return $this->shardName;
    }

    /**
     * Generated from protobuf field <code>string shardName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShardName($var)
    {
        GPBUtil::checkString($var, True);
        $this->shardName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @return string
     */
    public function getCollectionName()
    {
        return $this->collection_name;
    }

    /**
     * Generated from protobuf field <code>string collection_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string partition_name = 5;</code>
     * @return string
     */
    public function getPartitionName()
    {
        return $this->partition_name;
    }

    /**
     * Generated from protobuf field <code>string partition_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPartitionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->partition_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 dbID = 6;</code>
     * @return int|string
     */
    public function getDbID()
    {
        return $this->dbID;
    }

    /**
     * Generated from protobuf field <code>int64 dbID = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbID($var)
    {
        GPBUtil::checkInt64($var);
        $this->dbID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 7;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 partitionID = 8;</code>
     * @return int|string
     */
    public function getPartitionID()
    {
        return $this->partitionID;
    }

    /**
     * Generated from protobuf field <code>int64 partitionID = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->partitionID = $var;

        return $this;
    }

    /**
     * deprecated
     *
     * Generated from protobuf field <code>repeated int64 int64_primary_keys = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInt64PrimaryKeys()
    {
        return $this->int64_primary_keys;
    }

    /**
     * deprecated
     *
     * Generated from protobuf field <code>repeated int64 int64_primary_keys = 9;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInt64PrimaryKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->int64_primary_keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 timestamps = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimestamps()
    {
        return $this->timestamps;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 timestamps = 10;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimestamps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->timestamps = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 num_rows = 11;</code>
     * @return int|string
     */
    public function getNumRows()
    {
        return $this->num_rows;
    }

    /**
     * Generated from protobuf field <code>int64 num_rows = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->num_rows = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs primary_keys = 12;</code>
     * @return \Milvus\Proto\Schema\IDs|null
     */
    public function getPrimaryKeys()
    {
        return $this->primary_keys;
    }

    public function hasPrimaryKeys()
    {
        return isset($this->primary_keys);
    }

    public function clearPrimaryKeys()
    {
        unset($this->primary_keys);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs primary_keys = 12;</code>
     * @param \Milvus\Proto\Schema\IDs $var
     * @return $this
     */
    public function setPrimaryKeys($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Schema\IDs::class);
        $this->primary_keys = $var;

        return $this;
    }

}

