<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace Milvus\Proto\Msg;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.msg.MsgPosition</code>
 */
class MsgPosition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string channel_name = 1;</code>
     */
    protected $channel_name = '';
    /**
     * Generated from protobuf field <code>bytes msgID = 2;</code>
     */
    protected $msgID = '';
    /**
     * Generated from protobuf field <code>string msgGroup = 3;</code>
     */
    protected $msgGroup = '';
    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $channel_name
     *     @type string $msgID
     *     @type string $msgGroup
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string channel_name = 1;</code>
     * @return string
     */
    public function getChannelName()
    {
        return $this->channel_name;
    }

    /**
     * Generated from protobuf field <code>string channel_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setChannelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes msgID = 2;</code>
     * @return string
     */
    public function getMsgID()
    {
        return $this->msgID;
    }

    /**
     * Generated from protobuf field <code>bytes msgID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgID($var)
    {
        GPBUtil::checkString($var, False);
        $this->msgID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msgGroup = 3;</code>
     * @return string
     */
    public function getMsgGroup()
    {
        return $this->msgGroup;
    }

    /**
     * Generated from protobuf field <code>string msgGroup = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgGroup = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

}

