<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto

namespace Milvus\Proto\Proxy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.proxy.RefreshPolicyInfoCacheRequest</code>
 */
class RefreshPolicyInfoCacheRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>int32 opType = 2;</code>
     */
    protected $opType = 0;
    /**
     * Generated from protobuf field <code>string opKey = 3;</code>
     */
    protected $opKey = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type int $opType
     *     @type string $opKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 opType = 2;</code>
     * @return int
     */
    public function getOpType()
    {
        return $this->opType;
    }

    /**
     * Generated from protobuf field <code>int32 opType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOpType($var)
    {
        GPBUtil::checkInt32($var);
        $this->opType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string opKey = 3;</code>
     * @return string
     */
    public function getOpKey()
    {
        return $this->opKey;
    }

    /**
     * Generated from protobuf field <code>string opKey = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOpKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->opKey = $var;

        return $this;
    }

}

