<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto

namespace Milvus\Proto\Proxy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.proxy.SetRatesRequest</code>
 */
class SetRatesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.internal.Rate rates = 2;</code>
     */
    private $rates;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.QuotaState states = 3;</code>
     */
    private $states;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.ErrorCode codes = 4;</code>
     */
    private $codes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type array<\Milvus\Proto\Internal\Rate>|\Google\Protobuf\Internal\RepeatedField $rates
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $states
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $codes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.internal.Rate rates = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRates()
    {
        return $this->rates;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.internal.Rate rates = 2;</code>
     * @param array<\Milvus\Proto\Internal\Rate>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Internal\Rate::class);
        $this->rates = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.QuotaState states = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStates()
    {
        return $this->states;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.milvus.QuotaState states = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Milvus\Proto\Milvus\QuotaState::class);
        $this->states = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.ErrorCode codes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCodes()
    {
        return $this->codes;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.ErrorCode codes = 4;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Milvus\Proto\Common\ErrorCode::class);
        $this->codes = $arr;

        return $this;
    }

}

