<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index_coord.proto

namespace Milvus\Proto\Index;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.index.CreateIndexRequest</code>
 */
class CreateIndexRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     */
    protected $fieldID = 0;
    /**
     * Generated from protobuf field <code>string index_name = 3;</code>
     */
    protected $index_name = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 4;</code>
     */
    private $type_params;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 5;</code>
     */
    private $index_params;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>bool is_auto_index = 7;</code>
     */
    protected $is_auto_index = false;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair user_index_params = 8;</code>
     */
    private $user_index_params;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $collectionID
     *     @type int|string $fieldID
     *     @type string $index_name
     *     @type array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $type_params
     *     @type array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $index_params
     *     @type int|string $timestamp
     *     @type bool $is_auto_index
     *     @type array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $user_index_params
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\IndexCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     * @return int|string
     */
    public function getFieldID()
    {
        return $this->fieldID;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldID($var)
    {
        GPBUtil::checkInt64($var);
        $this->fieldID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string index_name = 3;</code>
     * @return string
     */
    public function getIndexName()
    {
        return $this->index_name;
    }

    /**
     * Generated from protobuf field <code>string index_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypeParams()
    {
        return $this->type_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 4;</code>
     * @param array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypeParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->type_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexParams()
    {
        return $this->index_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 5;</code>
     * @param array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->index_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_auto_index = 7;</code>
     * @return bool
     */
    public function getIsAutoIndex()
    {
        return $this->is_auto_index;
    }

    /**
     * Generated from protobuf field <code>bool is_auto_index = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAutoIndex($var)
    {
        GPBUtil::checkBool($var);
        $this->is_auto_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair user_index_params = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserIndexParams()
    {
        return $this->user_index_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair user_index_params = 8;</code>
     * @param array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserIndexParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->user_index_params = $arr;

        return $this;
    }

}

