<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index_coord.proto

namespace Milvus\Proto\Index;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.index.IndexInfo</code>
 */
class IndexInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     */
    protected $fieldID = 0;
    /**
     * Generated from protobuf field <code>string index_name = 3;</code>
     */
    protected $index_name = '';
    /**
     * Generated from protobuf field <code>int64 indexID = 4;</code>
     */
    protected $indexID = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 5;</code>
     */
    private $type_params;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 6;</code>
     */
    private $index_params;
    /**
     * index build progress
     * The real-time statistics may not be expected due to the existence of the compaction mechanism.
     *
     * Generated from protobuf field <code>int64 indexed_rows = 7;</code>
     */
    protected $indexed_rows = 0;
    /**
     * Generated from protobuf field <code>int64 total_rows = 8;</code>
     */
    protected $total_rows = 0;
    /**
     * index state
     *
     * Generated from protobuf field <code>.milvus.proto.common.IndexState state = 9;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>string index_state_fail_reason = 10;</code>
     */
    protected $index_state_fail_reason = '';
    /**
     * Generated from protobuf field <code>bool is_auto_index = 11;</code>
     */
    protected $is_auto_index = false;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair user_index_params = 12;</code>
     */
    private $user_index_params;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $collectionID
     *     @type int|string $fieldID
     *     @type string $index_name
     *     @type int|string $indexID
     *     @type array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $type_params
     *     @type array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $index_params
     *     @type int|string $indexed_rows
     *           index build progress
     *           The real-time statistics may not be expected due to the existence of the compaction mechanism.
     *     @type int|string $total_rows
     *     @type int $state
     *           index state
     *     @type string $index_state_fail_reason
     *     @type bool $is_auto_index
     *     @type array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $user_index_params
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\IndexCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     * @return int|string
     */
    public function getFieldID()
    {
        return $this->fieldID;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldID($var)
    {
        GPBUtil::checkInt64($var);
        $this->fieldID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string index_name = 3;</code>
     * @return string
     */
    public function getIndexName()
    {
        return $this->index_name;
    }

    /**
     * Generated from protobuf field <code>string index_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 indexID = 4;</code>
     * @return int|string
     */
    public function getIndexID()
    {
        return $this->indexID;
    }

    /**
     * Generated from protobuf field <code>int64 indexID = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndexID($var)
    {
        GPBUtil::checkInt64($var);
        $this->indexID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypeParams()
    {
        return $this->type_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair type_params = 5;</code>
     * @param array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypeParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->type_params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexParams()
    {
        return $this->index_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair index_params = 6;</code>
     * @param array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->index_params = $arr;

        return $this;
    }

    /**
     * index build progress
     * The real-time statistics may not be expected due to the existence of the compaction mechanism.
     *
     * Generated from protobuf field <code>int64 indexed_rows = 7;</code>
     * @return int|string
     */
    public function getIndexedRows()
    {
        return $this->indexed_rows;
    }

    /**
     * index build progress
     * The real-time statistics may not be expected due to the existence of the compaction mechanism.
     *
     * Generated from protobuf field <code>int64 indexed_rows = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndexedRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->indexed_rows = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_rows = 8;</code>
     * @return int|string
     */
    public function getTotalRows()
    {
        return $this->total_rows;
    }

    /**
     * Generated from protobuf field <code>int64 total_rows = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_rows = $var;

        return $this;
    }

    /**
     * index state
     *
     * Generated from protobuf field <code>.milvus.proto.common.IndexState state = 9;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * index state
     *
     * Generated from protobuf field <code>.milvus.proto.common.IndexState state = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\IndexState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string index_state_fail_reason = 10;</code>
     * @return string
     */
    public function getIndexStateFailReason()
    {
        return $this->index_state_fail_reason;
    }

    /**
     * Generated from protobuf field <code>string index_state_fail_reason = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexStateFailReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_state_fail_reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_auto_index = 11;</code>
     * @return bool
     */
    public function getIsAutoIndex()
    {
        return $this->is_auto_index;
    }

    /**
     * Generated from protobuf field <code>bool is_auto_index = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAutoIndex($var)
    {
        GPBUtil::checkBool($var);
        $this->is_auto_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair user_index_params = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserIndexParams()
    {
        return $this->user_index_params;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.common.KeyValuePair user_index_params = 12;</code>
     * @param array<\Milvus\Proto\Common\KeyValuePair>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserIndexParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Common\KeyValuePair::class);
        $this->user_index_params = $arr;

        return $this;
    }

}

