<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index_coord.proto

namespace Milvus\Proto\Index;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.index.RegisterNodeRequest</code>
 */
class RegisterNodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Address address = 2;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>int64 nodeID = 3;</code>
     */
    protected $nodeID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type \Milvus\Proto\Common\Address $address
     *     @type int|string $nodeID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\IndexCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Address address = 2;</code>
     * @return \Milvus\Proto\Common\Address|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Address address = 2;</code>
     * @param \Milvus\Proto\Common\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\Address::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nodeID = 3;</code>
     * @return int|string
     */
    public function getNodeID()
    {
        return $this->nodeID;
    }

    /**
     * Generated from protobuf field <code>int64 nodeID = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNodeID($var)
    {
        GPBUtil::checkInt64($var);
        $this->nodeID = $var;

        return $this;
    }

}

