<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index_coord.proto

namespace Milvus\Proto\Index;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.index.StorageConfig</code>
 */
class StorageConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string access_keyID = 2;</code>
     */
    protected $access_keyID = '';
    /**
     * Generated from protobuf field <code>string secret_access_key = 3;</code>
     */
    protected $secret_access_key = '';
    /**
     * Generated from protobuf field <code>bool useSSL = 4;</code>
     */
    protected $useSSL = false;
    /**
     * Generated from protobuf field <code>string bucket_name = 5;</code>
     */
    protected $bucket_name = '';
    /**
     * Generated from protobuf field <code>string root_path = 6;</code>
     */
    protected $root_path = '';
    /**
     * Generated from protobuf field <code>bool useIAM = 7;</code>
     */
    protected $useIAM = false;
    /**
     * Generated from protobuf field <code>string IAMEndpoint = 8;</code>
     */
    protected $IAMEndpoint = '';
    /**
     * Generated from protobuf field <code>string storage_type = 9;</code>
     */
    protected $storage_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type string $access_keyID
     *     @type string $secret_access_key
     *     @type bool $useSSL
     *     @type string $bucket_name
     *     @type string $root_path
     *     @type bool $useIAM
     *     @type string $IAMEndpoint
     *     @type string $storage_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\IndexCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_keyID = 2;</code>
     * @return string
     */
    public function getAccessKeyID()
    {
        return $this->access_keyID;
    }

    /**
     * Generated from protobuf field <code>string access_keyID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessKeyID($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_keyID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secret_access_key = 3;</code>
     * @return string
     */
    public function getSecretAccessKey()
    {
        return $this->secret_access_key;
    }

    /**
     * Generated from protobuf field <code>string secret_access_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSecretAccessKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret_access_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool useSSL = 4;</code>
     * @return bool
     */
    public function getUseSSL()
    {
        return $this->useSSL;
    }

    /**
     * Generated from protobuf field <code>bool useSSL = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseSSL($var)
    {
        GPBUtil::checkBool($var);
        $this->useSSL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bucket_name = 5;</code>
     * @return string
     */
    public function getBucketName()
    {
        return $this->bucket_name;
    }

    /**
     * Generated from protobuf field <code>string bucket_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBucketName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bucket_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string root_path = 6;</code>
     * @return string
     */
    public function getRootPath()
    {
        return $this->root_path;
    }

    /**
     * Generated from protobuf field <code>string root_path = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRootPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->root_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool useIAM = 7;</code>
     * @return bool
     */
    public function getUseIAM()
    {
        return $this->useIAM;
    }

    /**
     * Generated from protobuf field <code>bool useIAM = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseIAM($var)
    {
        GPBUtil::checkBool($var);
        $this->useIAM = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string IAMEndpoint = 8;</code>
     * @return string
     */
    public function getIAMEndpoint()
    {
        return $this->IAMEndpoint;
    }

    /**
     * Generated from protobuf field <code>string IAMEndpoint = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setIAMEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->IAMEndpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storage_type = 9;</code>
     * @return string
     */
    public function getStorageType()
    {
        return $this->storage_type;
    }

    /**
     * Generated from protobuf field <code>string storage_type = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setStorageType($var)
    {
        GPBUtil::checkString($var, True);
        $this->storage_type = $var;

        return $this;
    }

}

