<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.AssignSegmentIDRequest</code>
 */
class AssignSegmentIDRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 nodeID = 1;</code>
     */
    protected $nodeID = 0;
    /**
     * Generated from protobuf field <code>string peer_role = 2;</code>
     */
    protected $peer_role = '';
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentIDRequest segmentIDRequests = 3;</code>
     */
    private $segmentIDRequests;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $nodeID
     *     @type string $peer_role
     *     @type array<\Milvus\Proto\Data\SegmentIDRequest>|\Google\Protobuf\Internal\RepeatedField $segmentIDRequests
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 nodeID = 1;</code>
     * @return int|string
     */
    public function getNodeID()
    {
        return $this->nodeID;
    }

    /**
     * Generated from protobuf field <code>int64 nodeID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNodeID($var)
    {
        GPBUtil::checkInt64($var);
        $this->nodeID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string peer_role = 2;</code>
     * @return string
     */
    public function getPeerRole()
    {
        return $this->peer_role;
    }

    /**
     * Generated from protobuf field <code>string peer_role = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPeerRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer_role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentIDRequest segmentIDRequests = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSegmentIDRequests()
    {
        return $this->segmentIDRequests;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentIDRequest segmentIDRequests = 3;</code>
     * @param array<\Milvus\Proto\Data\SegmentIDRequest>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSegmentIDRequests($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\SegmentIDRequest::class);
        $this->segmentIDRequests = $arr;

        return $this;
    }

}

