<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.CheckPoint</code>
 */
class CheckPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     */
    protected $segmentID = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition position = 2;</code>
     */
    protected $position = null;
    /**
     * Generated from protobuf field <code>int64 num_of_rows = 3;</code>
     */
    protected $num_of_rows = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $segmentID
     *     @type \Milvus\Proto\Msg\MsgPosition $position
     *     @type int|string $num_of_rows
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     * @return int|string
     */
    public function getSegmentID()
    {
        return $this->segmentID;
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSegmentID($var)
    {
        GPBUtil::checkInt64($var);
        $this->segmentID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition position = 2;</code>
     * @return \Milvus\Proto\Msg\MsgPosition|null
     */
    public function getPosition()
    {
        return $this->position;
    }

    public function hasPosition()
    {
        return isset($this->position);
    }

    public function clearPosition()
    {
        unset($this->position);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition position = 2;</code>
     * @param \Milvus\Proto\Msg\MsgPosition $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Msg\MsgPosition::class);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 num_of_rows = 3;</code>
     * @return int|string
     */
    public function getNumOfRows()
    {
        return $this->num_of_rows;
    }

    /**
     * Generated from protobuf field <code>int64 num_of_rows = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumOfRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->num_of_rows = $var;

        return $this;
    }

}

