<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.CompactionPlan</code>
 */
class CompactionPlan extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 planID = 1;</code>
     */
    protected $planID = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.CompactionSegmentBinlogs segmentBinlogs = 2;</code>
     */
    private $segmentBinlogs;
    /**
     * Generated from protobuf field <code>uint64 start_time = 3;</code>
     */
    protected $start_time = 0;
    /**
     * Generated from protobuf field <code>int32 timeout_in_seconds = 4;</code>
     */
    protected $timeout_in_seconds = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.data.CompactionType type = 5;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>uint64 timetravel = 6;</code>
     */
    protected $timetravel = 0;
    /**
     * Generated from protobuf field <code>string channel = 7;</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>int64 collection_ttl = 8;</code>
     */
    protected $collection_ttl = 0;
    /**
     * Generated from protobuf field <code>int64 total_rows = 9;</code>
     */
    protected $total_rows = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $planID
     *     @type array<\Milvus\Proto\Data\CompactionSegmentBinlogs>|\Google\Protobuf\Internal\RepeatedField $segmentBinlogs
     *     @type int|string $start_time
     *     @type int $timeout_in_seconds
     *     @type int $type
     *     @type int|string $timetravel
     *     @type string $channel
     *     @type int|string $collection_ttl
     *     @type int|string $total_rows
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 planID = 1;</code>
     * @return int|string
     */
    public function getPlanID()
    {
        return $this->planID;
    }

    /**
     * Generated from protobuf field <code>int64 planID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPlanID($var)
    {
        GPBUtil::checkInt64($var);
        $this->planID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.CompactionSegmentBinlogs segmentBinlogs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSegmentBinlogs()
    {
        return $this->segmentBinlogs;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.CompactionSegmentBinlogs segmentBinlogs = 2;</code>
     * @param array<\Milvus\Proto\Data\CompactionSegmentBinlogs>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSegmentBinlogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\CompactionSegmentBinlogs::class);
        $this->segmentBinlogs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 start_time = 3;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Generated from protobuf field <code>uint64 start_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 timeout_in_seconds = 4;</code>
     * @return int
     */
    public function getTimeoutInSeconds()
    {
        return $this->timeout_in_seconds;
    }

    /**
     * Generated from protobuf field <code>int32 timeout_in_seconds = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeoutInSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->timeout_in_seconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.data.CompactionType type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.data.CompactionType type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Data\CompactionType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timetravel = 6;</code>
     * @return int|string
     */
    public function getTimetravel()
    {
        return $this->timetravel;
    }

    /**
     * Generated from protobuf field <code>uint64 timetravel = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimetravel($var)
    {
        GPBUtil::checkUint64($var);
        $this->timetravel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel = 7;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 collection_ttl = 8;</code>
     * @return int|string
     */
    public function getCollectionTtl()
    {
        return $this->collection_ttl;
    }

    /**
     * Generated from protobuf field <code>int64 collection_ttl = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionTtl($var)
    {
        GPBUtil::checkInt64($var);
        $this->collection_ttl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_rows = 9;</code>
     * @return int|string
     */
    public function getTotalRows()
    {
        return $this->total_rows;
    }

    /**
     * Generated from protobuf field <code>int64 total_rows = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_rows = $var;

        return $this;
    }

}

