<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.DropVirtualChannelSegment</code>
 */
class DropVirtualChannelSegment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     */
    protected $segmentID = 0;
    /**
     * Generated from protobuf field <code>int64 collectionID = 2;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog field2BinlogPaths = 3;</code>
     */
    private $field2BinlogPaths;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog field2StatslogPaths = 4;</code>
     */
    private $field2StatslogPaths;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog deltalogs = 5;</code>
     */
    private $deltalogs;
    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition startPosition = 6;</code>
     */
    protected $startPosition = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition checkPoint = 7;</code>
     */
    protected $checkPoint = null;
    /**
     * Generated from protobuf field <code>int64 numOfRows = 8;</code>
     */
    protected $numOfRows = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $segmentID
     *     @type int|string $collectionID
     *     @type array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $field2BinlogPaths
     *     @type array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $field2StatslogPaths
     *     @type array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $deltalogs
     *     @type \Milvus\Proto\Msg\MsgPosition $startPosition
     *     @type \Milvus\Proto\Msg\MsgPosition $checkPoint
     *     @type int|string $numOfRows
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     * @return int|string
     */
    public function getSegmentID()
    {
        return $this->segmentID;
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSegmentID($var)
    {
        GPBUtil::checkInt64($var);
        $this->segmentID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 2;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog field2BinlogPaths = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getField2BinlogPaths()
    {
        return $this->field2BinlogPaths;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog field2BinlogPaths = 3;</code>
     * @param array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setField2BinlogPaths($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\FieldBinlog::class);
        $this->field2BinlogPaths = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog field2StatslogPaths = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getField2StatslogPaths()
    {
        return $this->field2StatslogPaths;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog field2StatslogPaths = 4;</code>
     * @param array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setField2StatslogPaths($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\FieldBinlog::class);
        $this->field2StatslogPaths = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog deltalogs = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeltalogs()
    {
        return $this->deltalogs;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog deltalogs = 5;</code>
     * @param array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeltalogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\FieldBinlog::class);
        $this->deltalogs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition startPosition = 6;</code>
     * @return \Milvus\Proto\Msg\MsgPosition|null
     */
    public function getStartPosition()
    {
        return $this->startPosition;
    }

    public function hasStartPosition()
    {
        return isset($this->startPosition);
    }

    public function clearStartPosition()
    {
        unset($this->startPosition);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition startPosition = 6;</code>
     * @param \Milvus\Proto\Msg\MsgPosition $var
     * @return $this
     */
    public function setStartPosition($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Msg\MsgPosition::class);
        $this->startPosition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition checkPoint = 7;</code>
     * @return \Milvus\Proto\Msg\MsgPosition|null
     */
    public function getCheckPoint()
    {
        return $this->checkPoint;
    }

    public function hasCheckPoint()
    {
        return isset($this->checkPoint);
    }

    public function clearCheckPoint()
    {
        unset($this->checkPoint);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition checkPoint = 7;</code>
     * @param \Milvus\Proto\Msg\MsgPosition $var
     * @return $this
     */
    public function setCheckPoint($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Msg\MsgPosition::class);
        $this->checkPoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 numOfRows = 8;</code>
     * @return int|string
     */
    public function getNumOfRows()
    {
        return $this->numOfRows;
    }

    /**
     * Generated from protobuf field <code>int64 numOfRows = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumOfRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->numOfRows = $var;

        return $this;
    }

}

