<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.GcConfirmRequest</code>
 */
class GcConfirmRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 collection_id = 1;</code>
     */
    protected $collection_id = 0;
    /**
     * -1 means whole collection.
     *
     * Generated from protobuf field <code>int64 partition_id = 2;</code>
     */
    protected $partition_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $collection_id
     *     @type int|string $partition_id
     *           -1 means whole collection.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 collection_id = 1;</code>
     * @return int|string
     */
    public function getCollectionId()
    {
        return $this->collection_id;
    }

    /**
     * Generated from protobuf field <code>int64 collection_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->collection_id = $var;

        return $this;
    }

    /**
     * -1 means whole collection.
     *
     * Generated from protobuf field <code>int64 partition_id = 2;</code>
     * @return int|string
     */
    public function getPartitionId()
    {
        return $this->partition_id;
    }

    /**
     * -1 means whole collection.
     *
     * Generated from protobuf field <code>int64 partition_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPartitionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->partition_id = $var;

        return $this;
    }

}

