<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.SegmentStartPosition</code>
 */
class SegmentStartPosition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition start_position = 1;</code>
     */
    protected $start_position = null;
    /**
     * Generated from protobuf field <code>int64 segmentID = 2;</code>
     */
    protected $segmentID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Msg\MsgPosition $start_position
     *     @type int|string $segmentID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition start_position = 1;</code>
     * @return \Milvus\Proto\Msg\MsgPosition|null
     */
    public function getStartPosition()
    {
        return $this->start_position;
    }

    public function hasStartPosition()
    {
        return isset($this->start_position);
    }

    public function clearStartPosition()
    {
        unset($this->start_position);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition start_position = 1;</code>
     * @param \Milvus\Proto\Msg\MsgPosition $var
     * @return $this
     */
    public function setStartPosition($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Msg\MsgPosition::class);
        $this->start_position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 2;</code>
     * @return int|string
     */
    public function getSegmentID()
    {
        return $this->segmentID;
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSegmentID($var)
    {
        GPBUtil::checkInt64($var);
        $this->segmentID = $var;

        return $this;
    }

}

