<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.SegmentBinlogs</code>
 */
class SegmentBinlogs extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     */
    protected $segmentID = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog fieldBinlogs = 2;</code>
     */
    private $fieldBinlogs;
    /**
     * Generated from protobuf field <code>int64 num_of_rows = 3;</code>
     */
    protected $num_of_rows = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog statslogs = 4;</code>
     */
    private $statslogs;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog deltalogs = 5;</code>
     */
    private $deltalogs;
    /**
     * Generated from protobuf field <code>string insert_channel = 6;</code>
     */
    protected $insert_channel = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $segmentID
     *     @type array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $fieldBinlogs
     *     @type int|string $num_of_rows
     *     @type array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $statslogs
     *     @type array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $deltalogs
     *     @type string $insert_channel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     * @return int|string
     */
    public function getSegmentID()
    {
        return $this->segmentID;
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSegmentID($var)
    {
        GPBUtil::checkInt64($var);
        $this->segmentID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog fieldBinlogs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldBinlogs()
    {
        return $this->fieldBinlogs;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog fieldBinlogs = 2;</code>
     * @param array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldBinlogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\FieldBinlog::class);
        $this->fieldBinlogs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 num_of_rows = 3;</code>
     * @return int|string
     */
    public function getNumOfRows()
    {
        return $this->num_of_rows;
    }

    /**
     * Generated from protobuf field <code>int64 num_of_rows = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumOfRows($var)
    {
        GPBUtil::checkInt64($var);
        $this->num_of_rows = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog statslogs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStatslogs()
    {
        return $this->statslogs;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog statslogs = 4;</code>
     * @param array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStatslogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\FieldBinlog::class);
        $this->statslogs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog deltalogs = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeltalogs()
    {
        return $this->deltalogs;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.FieldBinlog deltalogs = 5;</code>
     * @param array<\Milvus\Proto\Data\FieldBinlog>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeltalogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\FieldBinlog::class);
        $this->deltalogs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string insert_channel = 6;</code>
     * @return string
     */
    public function getInsertChannel()
    {
        return $this->insert_channel;
    }

    /**
     * Generated from protobuf field <code>string insert_channel = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setInsertChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->insert_channel = $var;

        return $this;
    }

}

