<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.SegmentStateInfo</code>
 */
class SegmentStateInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     */
    protected $segmentID = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.SegmentState state = 2;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition start_position = 3;</code>
     */
    protected $start_position = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition end_position = 4;</code>
     */
    protected $end_position = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 5;</code>
     */
    protected $status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $segmentID
     *     @type int $state
     *     @type \Milvus\Proto\Msg\MsgPosition $start_position
     *     @type \Milvus\Proto\Msg\MsgPosition $end_position
     *     @type \Milvus\Proto\Common\Status $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     * @return int|string
     */
    public function getSegmentID()
    {
        return $this->segmentID;
    }

    /**
     * Generated from protobuf field <code>int64 segmentID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSegmentID($var)
    {
        GPBUtil::checkInt64($var);
        $this->segmentID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.SegmentState state = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.SegmentState state = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Common\SegmentState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition start_position = 3;</code>
     * @return \Milvus\Proto\Msg\MsgPosition|null
     */
    public function getStartPosition()
    {
        return $this->start_position;
    }

    public function hasStartPosition()
    {
        return isset($this->start_position);
    }

    public function clearStartPosition()
    {
        unset($this->start_position);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition start_position = 3;</code>
     * @param \Milvus\Proto\Msg\MsgPosition $var
     * @return $this
     */
    public function setStartPosition($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Msg\MsgPosition::class);
        $this->start_position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition end_position = 4;</code>
     * @return \Milvus\Proto\Msg\MsgPosition|null
     */
    public function getEndPosition()
    {
        return $this->end_position;
    }

    public function hasEndPosition()
    {
        return isset($this->end_position);
    }

    public function clearEndPosition()
    {
        unset($this->end_position);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition end_position = 4;</code>
     * @param \Milvus\Proto\Msg\MsgPosition $var
     * @return $this
     */
    public function setEndPosition($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Msg\MsgPosition::class);
        $this->end_position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 5;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 5;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\Status::class);
        $this->status = $var;

        return $this;
    }

}

