<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_coord.proto

namespace Milvus\Proto\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.data.VchannelInfo</code>
 */
class VchannelInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>string channelName = 2;</code>
     */
    protected $channelName = '';
    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition seek_position = 3;</code>
     */
    protected $seek_position = null;
    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo unflushedSegments = 4;</code>
     */
    private $unflushedSegments;
    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo flushedSegments = 5;</code>
     */
    private $flushedSegments;
    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo dropped_segments = 6;</code>
     */
    private $dropped_segments;
    /**
     * Generated from protobuf field <code>repeated int64 unflushedSegmentIds = 7;</code>
     */
    private $unflushedSegmentIds;
    /**
     * Generated from protobuf field <code>repeated int64 flushedSegmentIds = 8;</code>
     */
    private $flushedSegmentIds;
    /**
     * Generated from protobuf field <code>repeated int64 dropped_segmentIds = 9;</code>
     */
    private $dropped_segmentIds;
    /**
     * Generated from protobuf field <code>repeated int64 indexed_segmentIds = 10;</code>
     */
    private $indexed_segmentIds;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo indexed_segments = 11;</code>
     */
    private $indexed_segments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $collectionID
     *     @type string $channelName
     *     @type \Milvus\Proto\Msg\MsgPosition $seek_position
     *     @type array<\Milvus\Proto\Data\SegmentInfo>|\Google\Protobuf\Internal\RepeatedField $unflushedSegments
     *           deprecated, keep it for compatibility
     *     @type array<\Milvus\Proto\Data\SegmentInfo>|\Google\Protobuf\Internal\RepeatedField $flushedSegments
     *           deprecated, keep it for compatibility
     *     @type array<\Milvus\Proto\Data\SegmentInfo>|\Google\Protobuf\Internal\RepeatedField $dropped_segments
     *           deprecated, keep it for compatibility
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $unflushedSegmentIds
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $flushedSegmentIds
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $dropped_segmentIds
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $indexed_segmentIds
     *     @type array<\Milvus\Proto\Data\SegmentInfo>|\Google\Protobuf\Internal\RepeatedField $indexed_segments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DataCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channelName = 2;</code>
     * @return string
     */
    public function getChannelName()
    {
        return $this->channelName;
    }

    /**
     * Generated from protobuf field <code>string channelName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChannelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->channelName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition seek_position = 3;</code>
     * @return \Milvus\Proto\Msg\MsgPosition|null
     */
    public function getSeekPosition()
    {
        return $this->seek_position;
    }

    public function hasSeekPosition()
    {
        return isset($this->seek_position);
    }

    public function clearSeekPosition()
    {
        unset($this->seek_position);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.msg.MsgPosition seek_position = 3;</code>
     * @param \Milvus\Proto\Msg\MsgPosition $var
     * @return $this
     */
    public function setSeekPosition($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Msg\MsgPosition::class);
        $this->seek_position = $var;

        return $this;
    }

    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo unflushedSegments = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnflushedSegments()
    {
        return $this->unflushedSegments;
    }

    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo unflushedSegments = 4;</code>
     * @param array<\Milvus\Proto\Data\SegmentInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnflushedSegments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\SegmentInfo::class);
        $this->unflushedSegments = $arr;

        return $this;
    }

    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo flushedSegments = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFlushedSegments()
    {
        return $this->flushedSegments;
    }

    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo flushedSegments = 5;</code>
     * @param array<\Milvus\Proto\Data\SegmentInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFlushedSegments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\SegmentInfo::class);
        $this->flushedSegments = $arr;

        return $this;
    }

    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo dropped_segments = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDroppedSegments()
    {
        return $this->dropped_segments;
    }

    /**
     * deprecated, keep it for compatibility
     *
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo dropped_segments = 6;</code>
     * @param array<\Milvus\Proto\Data\SegmentInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDroppedSegments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\SegmentInfo::class);
        $this->dropped_segments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 unflushedSegmentIds = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnflushedSegmentIds()
    {
        return $this->unflushedSegmentIds;
    }

    /**
     * Generated from protobuf field <code>repeated int64 unflushedSegmentIds = 7;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnflushedSegmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->unflushedSegmentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 flushedSegmentIds = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFlushedSegmentIds()
    {
        return $this->flushedSegmentIds;
    }

    /**
     * Generated from protobuf field <code>repeated int64 flushedSegmentIds = 8;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFlushedSegmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->flushedSegmentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 dropped_segmentIds = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDroppedSegmentIds()
    {
        return $this->dropped_segmentIds;
    }

    /**
     * Generated from protobuf field <code>repeated int64 dropped_segmentIds = 9;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDroppedSegmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->dropped_segmentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 indexed_segmentIds = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexedSegmentIds()
    {
        return $this->indexed_segmentIds;
    }

    /**
     * Generated from protobuf field <code>repeated int64 indexed_segmentIds = 10;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexedSegmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->indexed_segmentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo indexed_segments = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexedSegments()
    {
        return $this->indexed_segments;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.data.SegmentInfo indexed_segments = 11;</code>
     * @param array<\Milvus\Proto\Data\SegmentInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexedSegments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Data\SegmentInfo::class);
        $this->indexed_segments = $arr;

        return $this;
    }

}

