<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: segcore.proto

namespace Milvus\Proto\Segcore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.segcore.LoadFieldMeta</code>
 */
class LoadFieldMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 min_timestamp = 1;</code>
     */
    protected $min_timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 max_timestamp = 2;</code>
     */
    protected $max_timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 row_count = 3;</code>
     */
    protected $row_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $min_timestamp
     *     @type int|string $max_timestamp
     *     @type int|string $row_count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Segcore::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 min_timestamp = 1;</code>
     * @return int|string
     */
    public function getMinTimestamp()
    {
        return $this->min_timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 min_timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_timestamp = 2;</code>
     * @return int|string
     */
    public function getMaxTimestamp()
    {
        return $this->max_timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 max_timestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 row_count = 3;</code>
     * @return int|string
     */
    public function getRowCount()
    {
        return $this->row_count;
    }

    /**
     * Generated from protobuf field <code>int64 row_count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRowCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->row_count = $var;

        return $this;
    }

}

