<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Milvus\Proto\Schema;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.schema.SearchResultData</code>
 */
class SearchResultData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 num_queries = 1;</code>
     */
    protected $num_queries = 0;
    /**
     * Generated from protobuf field <code>int64 top_k = 2;</code>
     */
    protected $top_k = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 3;</code>
     */
    private $fields_data;
    /**
     * Generated from protobuf field <code>repeated float scores = 4;</code>
     */
    private $scores;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 5;</code>
     */
    protected $ids = null;
    /**
     * Generated from protobuf field <code>repeated int64 topks = 6;</code>
     */
    private $topks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $num_queries
     *     @type int|string $top_k
     *     @type array<\Milvus\Proto\Schema\FieldData>|\Google\Protobuf\Internal\RepeatedField $fields_data
     *     @type array<float>|\Google\Protobuf\Internal\RepeatedField $scores
     *     @type \Milvus\Proto\Schema\IDs $ids
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $topks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 num_queries = 1;</code>
     * @return int|string
     */
    public function getNumQueries()
    {
        return $this->num_queries;
    }

    /**
     * Generated from protobuf field <code>int64 num_queries = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumQueries($var)
    {
        GPBUtil::checkInt64($var);
        $this->num_queries = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 top_k = 2;</code>
     * @return int|string
     */
    public function getTopK()
    {
        return $this->top_k;
    }

    /**
     * Generated from protobuf field <code>int64 top_k = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopK($var)
    {
        GPBUtil::checkInt64($var);
        $this->top_k = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldsData()
    {
        return $this->fields_data;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 3;</code>
     * @param array<\Milvus\Proto\Schema\FieldData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldsData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldData::class);
        $this->fields_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float scores = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScores()
    {
        return $this->scores;
    }

    /**
     * Generated from protobuf field <code>repeated float scores = 4;</code>
     * @param array<float>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScores($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->scores = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 5;</code>
     * @return \Milvus\Proto\Schema\IDs|null
     */
    public function getIds()
    {
        return $this->ids;
    }

    public function hasIds()
    {
        return isset($this->ids);
    }

    public function clearIds()
    {
        unset($this->ids);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 5;</code>
     * @param \Milvus\Proto\Schema\IDs $var
     * @return $this
     */
    public function setIds($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Schema\IDs::class);
        $this->ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 topks = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopks()
    {
        return $this->topks;
    }

    /**
     * Generated from protobuf field <code>repeated int64 topks = 6;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->topks = $arr;

        return $this;
    }

}

