<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd_meta.proto

namespace Milvus\Proto\Etcd;

use UnexpectedValueException;

/**
 * Protobuf type <code>milvus.proto.etcd.AliasState</code>
 */
class AliasState
{
    /**
     * Generated from protobuf enum <code>AliasCreated = 0;</code>
     */
    const AliasCreated = 0;
    /**
     * Generated from protobuf enum <code>AliasCreating = 1;</code>
     */
    const AliasCreating = 1;
    /**
     * Generated from protobuf enum <code>AliasDropping = 2;</code>
     */
    const AliasDropping = 2;
    /**
     * Generated from protobuf enum <code>AliasDropped = 3;</code>
     */
    const AliasDropped = 3;

    private static $valueToName = [
        self::AliasCreated => 'AliasCreated',
        self::AliasCreating => 'AliasCreating',
        self::AliasDropping => 'AliasDropping',
        self::AliasDropped => 'AliasDropped',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

