<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd_meta.proto

namespace Milvus\Proto\Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.etcd.AliasInfo</code>
 */
class AliasInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string alias_name = 1;</code>
     */
    protected $alias_name = '';
    /**
     * Generated from protobuf field <code>int64 collection_id = 2;</code>
     */
    protected $collection_id = 0;
    /**
     * Generated from protobuf field <code>uint64 created_time = 3;</code>
     */
    protected $created_time = 0;
    /**
     * To keep compatible with older version, default state is `Created`.
     *
     * Generated from protobuf field <code>.milvus.proto.etcd.AliasState state = 4;</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $alias_name
     *     @type int|string $collection_id
     *     @type int|string $created_time
     *     @type int $state
     *           To keep compatible with older version, default state is `Created`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EtcdMeta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string alias_name = 1;</code>
     * @return string
     */
    public function getAliasName()
    {
        return $this->alias_name;
    }

    /**
     * Generated from protobuf field <code>string alias_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAliasName($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 collection_id = 2;</code>
     * @return int|string
     */
    public function getCollectionId()
    {
        return $this->collection_id;
    }

    /**
     * Generated from protobuf field <code>int64 collection_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->collection_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 created_time = 3;</code>
     * @return int|string
     */
    public function getCreatedTime()
    {
        return $this->created_time;
    }

    /**
     * Generated from protobuf field <code>uint64 created_time = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->created_time = $var;

        return $this;
    }

    /**
     * To keep compatible with older version, default state is `Created`.
     *
     * Generated from protobuf field <code>.milvus.proto.etcd.AliasState state = 4;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * To keep compatible with older version, default state is `Created`.
     *
     * Generated from protobuf field <code>.milvus.proto.etcd.AliasState state = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Etcd\AliasState::class);
        $this->state = $var;

        return $this;
    }

}

