<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etcd_meta.proto

namespace Milvus\Proto\Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.etcd.FieldIndexInfo</code>
 */
class FieldIndexInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 filedID = 1;</code>
     */
    protected $filedID = 0;
    /**
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     */
    protected $indexID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $filedID
     *     @type int|string $indexID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EtcdMeta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 filedID = 1;</code>
     * @return int|string
     */
    public function getFiledID()
    {
        return $this->filedID;
    }

    /**
     * Generated from protobuf field <code>int64 filedID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFiledID($var)
    {
        GPBUtil::checkInt64($var);
        $this->filedID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     * @return int|string
     */
    public function getIndexID()
    {
        return $this->indexID;
    }

    /**
     * Generated from protobuf field <code>int64 indexID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndexID($var)
    {
        GPBUtil::checkInt64($var);
        $this->indexID = $var;

        return $this;
    }

}

