<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_coord.proto

namespace Milvus\Proto\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.query.GetLoadInfoResponse</code>
 */
class GetLoadInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 2;</code>
     */
    protected $schema = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.query.LoadType load_type = 3;</code>
     */
    protected $load_type = 0;
    /**
     * Generated from protobuf field <code>repeated int64 partitions = 4;</code>
     */
    private $partitions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\Status $status
     *     @type \Milvus\Proto\Schema\CollectionSchema $schema
     *     @type int $load_type
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $partitions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QueryCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 1;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 2;</code>
     * @return \Milvus\Proto\Schema\CollectionSchema|null
     */
    public function getSchema()
    {
        return $this->schema;
    }

    public function hasSchema()
    {
        return isset($this->schema);
    }

    public function clearSchema()
    {
        unset($this->schema);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 2;</code>
     * @param \Milvus\Proto\Schema\CollectionSchema $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Schema\CollectionSchema::class);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.query.LoadType load_type = 3;</code>
     * @return int
     */
    public function getLoadType()
    {
        return $this->load_type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.query.LoadType load_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLoadType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Query\LoadType::class);
        $this->load_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 partitions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPartitions()
    {
        return $this->partitions;
    }

    /**
     * Generated from protobuf field <code>repeated int64 partitions = 4;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPartitions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->partitions = $arr;

        return $this;
    }

}

