<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_coord.proto

namespace Milvus\Proto\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.query.LeaderView</code>
 */
class LeaderView extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 collection = 1;</code>
     */
    protected $collection = 0;
    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     */
    protected $channel = '';
    /**
     * Generated from protobuf field <code>map<int64, .milvus.proto.query.SegmentDist> segment_dist = 3;</code>
     */
    private $segment_dist;
    /**
     * Generated from protobuf field <code>repeated int64 growing_segmentIDs = 4;</code>
     */
    private $growing_segmentIDs;
    /**
     * Generated from protobuf field <code>map<int64, .milvus.proto.msg.MsgPosition> growing_segments = 5;</code>
     */
    private $growing_segments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $collection
     *     @type string $channel
     *     @type array|\Google\Protobuf\Internal\MapField $segment_dist
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $growing_segmentIDs
     *     @type array|\Google\Protobuf\Internal\MapField $growing_segments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QueryCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 collection = 1;</code>
     * @return int|string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>int64 collection = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkInt64($var);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int64, .milvus.proto.query.SegmentDist> segment_dist = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSegmentDist()
    {
        return $this->segment_dist;
    }

    /**
     * Generated from protobuf field <code>map<int64, .milvus.proto.query.SegmentDist> segment_dist = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSegmentDist($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT64, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Query\SegmentDist::class);
        $this->segment_dist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 growing_segmentIDs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGrowingSegmentIDs()
    {
        return $this->growing_segmentIDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 growing_segmentIDs = 4;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGrowingSegmentIDs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->growing_segmentIDs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int64, .milvus.proto.msg.MsgPosition> growing_segments = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getGrowingSegments()
    {
        return $this->growing_segments;
    }

    /**
     * Generated from protobuf field <code>map<int64, .milvus.proto.msg.MsgPosition> growing_segments = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setGrowingSegments($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT64, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Msg\MsgPosition::class);
        $this->growing_segments = $arr;

        return $this;
    }

}

