<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_coord.proto

namespace Milvus\Proto\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.query.LoadPartitionsRequest</code>
 */
class LoadPartitionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>int64 dbID = 2;</code>
     */
    protected $dbID = 0;
    /**
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>repeated int64 partitionIDs = 4;</code>
     */
    private $partitionIDs;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 5;</code>
     */
    protected $schema = null;
    /**
     * Generated from protobuf field <code>int32 replica_number = 6;</code>
     */
    protected $replica_number = 0;
    /**
     * fieldID -> indexID
     *
     * Generated from protobuf field <code>map<int64, int64> field_indexID = 7;</code>
     */
    private $field_indexID;
    /**
     * Generated from protobuf field <code>bool refresh = 8;</code>
     */
    protected $refresh = false;
    /**
     * resource group names
     *
     * Generated from protobuf field <code>repeated string resource_groups = 9;</code>
     */
    private $resource_groups;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type int|string $dbID
     *     @type int|string $collectionID
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $partitionIDs
     *     @type \Milvus\Proto\Schema\CollectionSchema $schema
     *     @type int $replica_number
     *     @type array|\Google\Protobuf\Internal\MapField $field_indexID
     *           fieldID -> indexID
     *     @type bool $refresh
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $resource_groups
     *           resource group names
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QueryCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 dbID = 2;</code>
     * @return int|string
     */
    public function getDbID()
    {
        return $this->dbID;
    }

    /**
     * Generated from protobuf field <code>int64 dbID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbID($var)
    {
        GPBUtil::checkInt64($var);
        $this->dbID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 partitionIDs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPartitionIDs()
    {
        return $this->partitionIDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 partitionIDs = 4;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPartitionIDs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->partitionIDs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 5;</code>
     * @return \Milvus\Proto\Schema\CollectionSchema|null
     */
    public function getSchema()
    {
        return $this->schema;
    }

    public function hasSchema()
    {
        return isset($this->schema);
    }

    public function clearSchema()
    {
        unset($this->schema);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.CollectionSchema schema = 5;</code>
     * @param \Milvus\Proto\Schema\CollectionSchema $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Schema\CollectionSchema::class);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 replica_number = 6;</code>
     * @return int
     */
    public function getReplicaNumber()
    {
        return $this->replica_number;
    }

    /**
     * Generated from protobuf field <code>int32 replica_number = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setReplicaNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->replica_number = $var;

        return $this;
    }

    /**
     * fieldID -> indexID
     *
     * Generated from protobuf field <code>map<int64, int64> field_indexID = 7;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFieldIndexID()
    {
        return $this->field_indexID;
    }

    /**
     * fieldID -> indexID
     *
     * Generated from protobuf field <code>map<int64, int64> field_indexID = 7;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFieldIndexID($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT64, \Google\Protobuf\Internal\GPBType::INT64);
        $this->field_indexID = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool refresh = 8;</code>
     * @return bool
     */
    public function getRefresh()
    {
        return $this->refresh;
    }

    /**
     * Generated from protobuf field <code>bool refresh = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setRefresh($var)
    {
        GPBUtil::checkBool($var);
        $this->refresh = $var;

        return $this;
    }

    /**
     * resource group names
     *
     * Generated from protobuf field <code>repeated string resource_groups = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResourceGroups()
    {
        return $this->resource_groups;
    }

    /**
     * resource group names
     *
     * Generated from protobuf field <code>repeated string resource_groups = 9;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResourceGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->resource_groups = $arr;

        return $this;
    }

}

