<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_coord.proto

namespace Milvus\Proto\Query;

use UnexpectedValueException;

/**
 * Protobuf type <code>milvus.proto.query.LoadType</code>
 */
class LoadType
{
    /**
     * Generated from protobuf enum <code>UnKnownType = 0;</code>
     */
    const UnKnownType = 0;
    /**
     * Generated from protobuf enum <code>LoadPartition = 1;</code>
     */
    const LoadPartition = 1;
    /**
     * Generated from protobuf enum <code>LoadCollection = 2;</code>
     */
    const LoadCollection = 2;

    private static $valueToName = [
        self::UnKnownType => 'UnKnownType',
        self::LoadPartition => 'LoadPartition',
        self::LoadCollection => 'LoadCollection',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

