<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_coord.proto

namespace Milvus\Proto\Query;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.query.UnsubscribeChannelInfo</code>
 */
class UnsubscribeChannelInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 nodeID = 1;</code>
     */
    protected $nodeID = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.query.UnsubscribeChannels collection_channels = 2;</code>
     */
    private $collection_channels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $nodeID
     *     @type array<\Milvus\Proto\Query\UnsubscribeChannels>|\Google\Protobuf\Internal\RepeatedField $collection_channels
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\QueryCoord::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 nodeID = 1;</code>
     * @return int|string
     */
    public function getNodeID()
    {
        return $this->nodeID;
    }

    /**
     * Generated from protobuf field <code>int64 nodeID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNodeID($var)
    {
        GPBUtil::checkInt64($var);
        $this->nodeID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.query.UnsubscribeChannels collection_channels = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCollectionChannels()
    {
        return $this->collection_channels;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.query.UnsubscribeChannels collection_channels = 2;</code>
     * @param array<\Milvus\Proto\Query\UnsubscribeChannels>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCollectionChannels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Query\UnsubscribeChannels::class);
        $this->collection_channels = $arr;

        return $this;
    }

}

