<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

namespace Milvus\Proto\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.internal.FieldStats</code>
 */
class FieldStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     */
    protected $collectionID = 0;
    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     */
    protected $fieldID = 0;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.internal.IndexStats index_stats = 3;</code>
     */
    private $index_stats;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $collectionID
     *     @type int|string $fieldID
     *     @type array<\Milvus\Proto\Internal\IndexStats>|\Google\Protobuf\Internal\RepeatedField $index_stats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * Generated from protobuf field <code>int64 collectionID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     * @return int|string
     */
    public function getFieldID()
    {
        return $this->fieldID;
    }

    /**
     * Generated from protobuf field <code>int64 fieldID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldID($var)
    {
        GPBUtil::checkInt64($var);
        $this->fieldID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.internal.IndexStats index_stats = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexStats()
    {
        return $this->index_stats;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.internal.IndexStats index_stats = 3;</code>
     * @param array<\Milvus\Proto\Internal\IndexStats>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Internal\IndexStats::class);
        $this->index_stats = $arr;

        return $this;
    }

}

