<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

namespace Milvus\Proto\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.internal.GetStatisticsRequest</code>
 */
class GetStatisticsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>int64 dbID = 2;</code>
     */
    protected $dbID = 0;
    /**
     * The collection you want get statistics
     *
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     */
    protected $collectionID = 0;
    /**
     * The partitions you want get statistics
     *
     * Generated from protobuf field <code>repeated int64 partitionIDs = 4;</code>
     */
    private $partitionIDs;
    /**
     * timestamp of the statistics
     *
     * Generated from protobuf field <code>uint64 travel_timestamp = 5;</code>
     */
    protected $travel_timestamp = 0;
    /**
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 6;</code>
     */
    protected $guarantee_timestamp = 0;
    /**
     * Generated from protobuf field <code>uint64 timeout_timestamp = 7;</code>
     */
    protected $timeout_timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type int|string $dbID
     *           Not useful for now
     *     @type int|string $collectionID
     *           The collection you want get statistics
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $partitionIDs
     *           The partitions you want get statistics
     *     @type int|string $travel_timestamp
     *           timestamp of the statistics
     *     @type int|string $guarantee_timestamp
     *     @type int|string $timeout_timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>int64 dbID = 2;</code>
     * @return int|string
     */
    public function getDbID()
    {
        return $this->dbID;
    }

    /**
     * Not useful for now
     *
     * Generated from protobuf field <code>int64 dbID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDbID($var)
    {
        GPBUtil::checkInt64($var);
        $this->dbID = $var;

        return $this;
    }

    /**
     * The collection you want get statistics
     *
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     * @return int|string
     */
    public function getCollectionID()
    {
        return $this->collectionID;
    }

    /**
     * The collection you want get statistics
     *
     * Generated from protobuf field <code>int64 collectionID = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectionID($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectionID = $var;

        return $this;
    }

    /**
     * The partitions you want get statistics
     *
     * Generated from protobuf field <code>repeated int64 partitionIDs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPartitionIDs()
    {
        return $this->partitionIDs;
    }

    /**
     * The partitions you want get statistics
     *
     * Generated from protobuf field <code>repeated int64 partitionIDs = 4;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPartitionIDs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->partitionIDs = $arr;

        return $this;
    }

    /**
     * timestamp of the statistics
     *
     * Generated from protobuf field <code>uint64 travel_timestamp = 5;</code>
     * @return int|string
     */
    public function getTravelTimestamp()
    {
        return $this->travel_timestamp;
    }

    /**
     * timestamp of the statistics
     *
     * Generated from protobuf field <code>uint64 travel_timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTravelTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->travel_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 6;</code>
     * @return int|string
     */
    public function getGuaranteeTimestamp()
    {
        return $this->guarantee_timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 guarantee_timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuaranteeTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->guarantee_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timeout_timestamp = 7;</code>
     * @return int|string
     */
    public function getTimeoutTimestamp()
    {
        return $this->timeout_timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timeout_timestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeoutTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timeout_timestamp = $var;

        return $this;
    }

}

