<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

namespace Milvus\Proto\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.internal.RetrieveResults</code>
 */
class RetrieveResults extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 2;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>int64 reqID = 3;</code>
     */
    protected $reqID = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 4;</code>
     */
    protected $ids = null;
    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     */
    private $fields_data;
    /**
     * Generated from protobuf field <code>repeated int64 sealed_segmentIDs_retrieved = 6;</code>
     */
    private $sealed_segmentIDs_retrieved;
    /**
     * Generated from protobuf field <code>repeated string channelIDs_retrieved = 7;</code>
     */
    private $channelIDs_retrieved;
    /**
     * Generated from protobuf field <code>repeated int64 global_sealed_segmentIDs = 8;</code>
     */
    private $global_sealed_segmentIDs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Common\MsgBase $base
     *     @type \Milvus\Proto\Common\Status $status
     *     @type int|string $reqID
     *     @type \Milvus\Proto\Schema\IDs $ids
     *     @type array<\Milvus\Proto\Schema\FieldData>|\Google\Protobuf\Internal\RepeatedField $fields_data
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $sealed_segmentIDs_retrieved
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $channelIDs_retrieved
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $global_sealed_segmentIDs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @return \Milvus\Proto\Common\MsgBase|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.MsgBase base = 1;</code>
     * @param \Milvus\Proto\Common\MsgBase $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\MsgBase::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 2;</code>
     * @return \Milvus\Proto\Common\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.common.Status status = 2;</code>
     * @param \Milvus\Proto\Common\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Common\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reqID = 3;</code>
     * @return int|string
     */
    public function getReqID()
    {
        return $this->reqID;
    }

    /**
     * Generated from protobuf field <code>int64 reqID = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReqID($var)
    {
        GPBUtil::checkInt64($var);
        $this->reqID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 4;</code>
     * @return \Milvus\Proto\Schema\IDs|null
     */
    public function getIds()
    {
        return $this->ids;
    }

    public function hasIds()
    {
        return isset($this->ids);
    }

    public function clearIds()
    {
        unset($this->ids);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.IDs ids = 4;</code>
     * @param \Milvus\Proto\Schema\IDs $var
     * @return $this
     */
    public function setIds($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Schema\IDs::class);
        $this->ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldsData()
    {
        return $this->fields_data;
    }

    /**
     * Generated from protobuf field <code>repeated .milvus.proto.schema.FieldData fields_data = 5;</code>
     * @param array<\Milvus\Proto\Schema\FieldData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldsData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Milvus\Proto\Schema\FieldData::class);
        $this->fields_data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 sealed_segmentIDs_retrieved = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSealedSegmentIDsRetrieved()
    {
        return $this->sealed_segmentIDs_retrieved;
    }

    /**
     * Generated from protobuf field <code>repeated int64 sealed_segmentIDs_retrieved = 6;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSealedSegmentIDsRetrieved($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->sealed_segmentIDs_retrieved = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string channelIDs_retrieved = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChannelIDsRetrieved()
    {
        return $this->channelIDs_retrieved;
    }

    /**
     * Generated from protobuf field <code>repeated string channelIDs_retrieved = 7;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChannelIDsRetrieved($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->channelIDs_retrieved = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 global_sealed_segmentIDs = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGlobalSealedSegmentIDs()
    {
        return $this->global_sealed_segmentIDs;
    }

    /**
     * Generated from protobuf field <code>repeated int64 global_sealed_segmentIDs = 8;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGlobalSealedSegmentIDs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->global_sealed_segmentIDs = $arr;

        return $this;
    }

}

