<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plan.proto

namespace Milvus\Proto\Plan;

use UnexpectedValueException;

/**
 * Protobuf type <code>milvus.proto.plan.ArithOpType</code>
 */
class ArithOpType
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>Add = 1;</code>
     */
    const Add = 1;
    /**
     * Generated from protobuf enum <code>Sub = 2;</code>
     */
    const Sub = 2;
    /**
     * Generated from protobuf enum <code>Mul = 3;</code>
     */
    const Mul = 3;
    /**
     * Generated from protobuf enum <code>Div = 4;</code>
     */
    const Div = 4;
    /**
     * Generated from protobuf enum <code>Mod = 5;</code>
     */
    const Mod = 5;

    private static $valueToName = [
        self::Unknown => 'Unknown',
        self::Add => 'Add',
        self::Sub => 'Sub',
        self::Mul => 'Mul',
        self::Div => 'Div',
        self::Mod => 'Mod',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

