<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plan.proto

namespace Milvus\Proto\Plan;

if (false) {
    /**
     * This class is deprecated. Use Milvus\Proto\Plan\BinaryExpr\BinaryOp instead.
     * @deprecated
     */
    class BinaryExpr_BinaryOp {}
}
class_exists(BinaryExpr\BinaryOp::class);
@trigger_error('Milvus\Proto\Plan\BinaryExpr_BinaryOp is deprecated and will be removed in the next major release. Use Milvus\Proto\Plan\BinaryExpr\BinaryOp instead', E_USER_DEPRECATED);

