<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plan.proto

namespace Milvus\Proto\Plan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.plan.ColumnInfo</code>
 */
class ColumnInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 field_id = 1;</code>
     */
    protected $field_id = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType data_type = 2;</code>
     */
    protected $data_type = 0;
    /**
     * Generated from protobuf field <code>bool is_primary_key = 3;</code>
     */
    protected $is_primary_key = false;
    /**
     * Generated from protobuf field <code>bool is_autoID = 4;</code>
     */
    protected $is_autoID = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $field_id
     *     @type int $data_type
     *     @type bool $is_primary_key
     *     @type bool $is_autoID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plan::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 field_id = 1;</code>
     * @return int|string
     */
    public function getFieldId()
    {
        return $this->field_id;
    }

    /**
     * Generated from protobuf field <code>int64 field_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFieldId($var)
    {
        GPBUtil::checkInt64($var);
        $this->field_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType data_type = 2;</code>
     * @return int
     */
    public function getDataType()
    {
        return $this->data_type;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.schema.DataType data_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDataType($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Schema\DataType::class);
        $this->data_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_primary_key = 3;</code>
     * @return bool
     */
    public function getIsPrimaryKey()
    {
        return $this->is_primary_key;
    }

    /**
     * Generated from protobuf field <code>bool is_primary_key = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPrimaryKey($var)
    {
        GPBUtil::checkBool($var);
        $this->is_primary_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_autoID = 4;</code>
     * @return bool
     */
    public function getIsAutoID()
    {
        return $this->is_autoID;
    }

    /**
     * Generated from protobuf field <code>bool is_autoID = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAutoID($var)
    {
        GPBUtil::checkBool($var);
        $this->is_autoID = $var;

        return $this;
    }

}

