<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plan.proto

namespace Milvus\Proto\Plan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.plan.PlanNode</code>
 */
class PlanNode extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 output_field_ids = 3;</code>
     */
    private $output_field_ids;
    protected $node;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Plan\VectorANNS $vector_anns
     *     @type \Milvus\Proto\Plan\Expr $predicates
     *           deprecated, use query instead.
     *     @type \Milvus\Proto\Plan\QueryPlanNode $query
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $output_field_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plan::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.VectorANNS vector_anns = 1;</code>
     * @return \Milvus\Proto\Plan\VectorANNS|null
     */
    public function getVectorAnns()
    {
        return $this->readOneof(1);
    }

    public function hasVectorAnns()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.VectorANNS vector_anns = 1;</code>
     * @param \Milvus\Proto\Plan\VectorANNS $var
     * @return $this
     */
    public function setVectorAnns($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Plan\VectorANNS::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * deprecated, use query instead.
     *
     * Generated from protobuf field <code>.milvus.proto.plan.Expr predicates = 2;</code>
     * @return \Milvus\Proto\Plan\Expr|null
     */
    public function getPredicates()
    {
        return $this->readOneof(2);
    }

    public function hasPredicates()
    {
        return $this->hasOneof(2);
    }

    /**
     * deprecated, use query instead.
     *
     * Generated from protobuf field <code>.milvus.proto.plan.Expr predicates = 2;</code>
     * @param \Milvus\Proto\Plan\Expr $var
     * @return $this
     */
    public function setPredicates($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Plan\Expr::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.QueryPlanNode query = 4;</code>
     * @return \Milvus\Proto\Plan\QueryPlanNode|null
     */
    public function getQuery()
    {
        return $this->readOneof(4);
    }

    public function hasQuery()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.QueryPlanNode query = 4;</code>
     * @param \Milvus\Proto\Plan\QueryPlanNode $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Plan\QueryPlanNode::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 output_field_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputFieldIds()
    {
        return $this->output_field_ids;
    }

    /**
     * Generated from protobuf field <code>repeated int64 output_field_ids = 3;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputFieldIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->output_field_ids = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getNode()
    {
        return $this->whichOneof("node");
    }

}

