<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plan.proto

namespace Milvus\Proto\Plan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.plan.UnaryRangeExpr</code>
 */
class UnaryRangeExpr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.plan.ColumnInfo column_info = 1;</code>
     */
    protected $column_info = null;
    /**
     * Generated from protobuf field <code>.milvus.proto.plan.OpType op = 2;</code>
     */
    protected $op = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.plan.GenericValue value = 3;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Milvus\Proto\Plan\ColumnInfo $column_info
     *     @type int $op
     *     @type \Milvus\Proto\Plan\GenericValue $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plan::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.ColumnInfo column_info = 1;</code>
     * @return \Milvus\Proto\Plan\ColumnInfo|null
     */
    public function getColumnInfo()
    {
        return $this->column_info;
    }

    public function hasColumnInfo()
    {
        return isset($this->column_info);
    }

    public function clearColumnInfo()
    {
        unset($this->column_info);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.ColumnInfo column_info = 1;</code>
     * @param \Milvus\Proto\Plan\ColumnInfo $var
     * @return $this
     */
    public function setColumnInfo($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Plan\ColumnInfo::class);
        $this->column_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.OpType op = 2;</code>
     * @return int
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.OpType op = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Plan\OpType::class);
        $this->op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.GenericValue value = 3;</code>
     * @return \Milvus\Proto\Plan\GenericValue|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.GenericValue value = 3;</code>
     * @param \Milvus\Proto\Plan\GenericValue $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Plan\GenericValue::class);
        $this->value = $var;

        return $this;
    }

}

