<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plan.proto

namespace Milvus\Proto\Plan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>milvus.proto.plan.UnaryExpr</code>
 */
class UnaryExpr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.milvus.proto.plan.UnaryExpr.UnaryOp op = 1;</code>
     */
    protected $op = 0;
    /**
     * Generated from protobuf field <code>.milvus.proto.plan.Expr child = 2;</code>
     */
    protected $child = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $op
     *     @type \Milvus\Proto\Plan\Expr $child
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Plan::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.UnaryExpr.UnaryOp op = 1;</code>
     * @return int
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.UnaryExpr.UnaryOp op = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, \Milvus\Proto\Plan\UnaryExpr\UnaryOp::class);
        $this->op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.Expr child = 2;</code>
     * @return \Milvus\Proto\Plan\Expr|null
     */
    public function getChild()
    {
        return $this->child;
    }

    public function hasChild()
    {
        return isset($this->child);
    }

    public function clearChild()
    {
        unset($this->child);
    }

    /**
     * Generated from protobuf field <code>.milvus.proto.plan.Expr child = 2;</code>
     * @param \Milvus\Proto\Plan\Expr $var
     * @return $this
     */
    public function setChild($var)
    {
        GPBUtil::checkMessage($var, \Milvus\Proto\Plan\Expr::class);
        $this->child = $var;

        return $this;
    }

}

